DECLARE @SQL VARCHAR(200)
declare @maxIdLogData bigint
BEGIN

    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'AUI_ISSUER_PRODUCT_PARAMETER')
        BEGIN
            DROP SYNONYM AUI_ISSUER_PRODUCT_PARAMETER;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].AUI_ISSUER_PRODUCT_PARAMETER FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].AUI_ISSUER_PRODUCT_PARAMETER';
    EXEC sp_sqlexec @SQL;

    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'AUI_PAYMENT_MEDIA_STATUS')
        BEGIN
            DROP SYNONYM AUI_PAYMENT_MEDIA_STATUS;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].AUI_PAYMENT_MEDIA_STATUS FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].AUI_PAYMENT_MEDIA_STATUS';
    EXEC sp_sqlexec @SQL;

    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'AUI_PAYMENT_MEDIA_PARAMETER')
        BEGIN
            DROP SYNONYM AUI_PAYMENT_MEDIA_PARAMETER;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].AUI_PAYMENT_MEDIA_PARAMETER FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].AUI_PAYMENT_MEDIA_PARAMETER';
    EXEC sp_sqlexec @SQL;

    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'AU_PARAMETER')
        BEGIN
            DROP SYNONYM AU_PARAMETER;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].AU_PARAMETER FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].AU_PARAMETER';
    EXEC sp_sqlexec @SQL;


--CREATE SYNONYM [dbo].AUI_ACCOUNT_RELATION_CRED_LINE FOR [cpm_testE6_team3_aas].[dbo].AUI_ACCOUNT_RELATION_CRED_LINE
    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'AUI_ACCOUNT_RELATION_CRED_LINE')
        BEGIN
            DROP SYNONYM AUI_ACCOUNT_RELATION_CRED_LINE;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].AUI_ACCOUNT_RELATION_CRED_LINE FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].AUI_ACCOUNT_RELATION_CRED_LINE';
    EXEC sp_sqlexec @SQL;
    --CREATE SYNONYM [dbo].AUI_CREDIT_GENERAL_ACCOUNT FOR [cpm_testE6_team3_aas].[dbo].AUI_CREDIT_GENERAL_ACCOUNT
    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'AUI_CREDIT_GENERAL_ACCOUNT')
        BEGIN
            DROP SYNONYM AUI_CREDIT_GENERAL_ACCOUNT;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].AUI_CREDIT_GENERAL_ACCOUNT FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].AUI_CREDIT_GENERAL_ACCOUNT';
    EXEC sp_sqlexec @SQL;
    --CREATE SYNONYM [dbo].AUI_TRX_ISSUER_DATA FOR [cpm_testE6_team3_aas].[dbo].AUI_TRX_ISSUER_DATA
    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'AUI_TRX_ISSUER_DATA')
        BEGIN
            DROP SYNONYM AUI_TRX_ISSUER_DATA;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].AUI_TRX_ISSUER_DATA FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].AUI_TRX_ISSUER_DATA';
    EXEC sp_sqlexec @SQL;

    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'AUI_TRX_ISSUER_DATA')
        BEGIN
            DROP SYNONYM AUI_TRX_ISSUER_DATA;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].AUI_TRX_ISSUER_DATA FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].AUI_TRX_ISSUER_DATA';
    EXEC sp_sqlexec @SQL;
    --CREATE SYNONYM [dbo].AUI_GENERAL_ACCOUNT_CRED_LINE FOR [cpm_testE6_team3_aas].[dbo].AUI_GENERAL_ACCOUNT_CRED_LINE
    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'AUI_GENERAL_ACCOUNT_CRED_LINE')
        BEGIN
            DROP SYNONYM AUI_GENERAL_ACCOUNT_CRED_LINE;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].AUI_GENERAL_ACCOUNT_CRED_LINE FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].AUI_GENERAL_ACCOUNT_CRED_LINE';
    EXEC sp_sqlexec @SQL;

    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'AUI_AFFECTED_CREDIT_LINES')
        BEGIN
            DROP SYNONYM AUI_AFFECTED_CREDIT_LINES;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].AUI_AFFECTED_CREDIT_LINES FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].AUI_AFFECTED_CREDIT_LINES';
    EXEC sp_sqlexec @SQL;

    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'AUI_PAYMENT_MEDIA_RELATION')
        BEGIN
            DROP SYNONYM AUI_PAYMENT_MEDIA_RELATION;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].AUI_PAYMENT_MEDIA_RELATION FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].AUI_PAYMENT_MEDIA_RELATION';
    EXEC sp_sqlexec @SQL;

    --CREATE SYNONYM [dbo].AU_OPEN_TRANSACTION FOR [cpm_testE6_team3_aas].[dbo].AU_OPEN_TRANSACTION
    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'AU_OPEN_TRANSACTION')
        BEGIN
            DROP SYNONYM AU_OPEN_TRANSACTION;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].AU_OPEN_TRANSACTION FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].AU_OPEN_TRANSACTION';
    EXEC sp_sqlexec @SQL;

    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'AUI_TRX_ISSUER_DATA')
        BEGIN
            DROP SYNONYM AUI_TRX_ISSUER_DATA;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].AUI_TRX_ISSUER_DATA FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].AUI_TRX_ISSUER_DATA';
    EXEC sp_sqlexec @SQL;

    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'AUI_ISSUER_TRX_REPLICATE')
        BEGIN
            DROP SYNONYM AUI_ISSUER_TRX_REPLICATE;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].AUI_ISSUER_TRX_REPLICATE FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].AUI_ISSUER_TRX_REPLICATE';
    EXEC sp_sqlexec @SQL;

    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'AUI_TRANSACTION_PROFILE')
        BEGIN
            DROP SYNONYM AUI_TRANSACTION_PROFILE;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].AUI_TRANSACTION_PROFILE FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].AUI_TRANSACTION_PROFILE';
    EXEC sp_sqlexec @SQL;


    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'AU_PENDING_TRANSACTION')
        BEGIN
            DROP SYNONYM AU_PENDING_TRANSACTION;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].AU_PENDING_TRANSACTION FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].AU_PENDING_TRANSACTION';
    EXEC sp_sqlexec @SQL;


    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'AU_TRANSACTION_TYPE')
        BEGIN
            DROP SYNONYM AU_TRANSACTION_TYPE;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].AU_TRANSACTION_TYPE FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].AU_TRANSACTION_TYPE';
    EXEC sp_sqlexec @SQL;

    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'T_KEY')
        BEGIN
            DROP SYNONYM T_KEY;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].T_KEY FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].T_KEY';
    EXEC sp_sqlexec @SQL;

    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'AUI_PRODUCT')
        BEGIN
            DROP SYNONYM AUI_PRODUCT;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].AUI_PRODUCT FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].AUI_PRODUCT';
    EXEC sp_sqlexec @SQL;

    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'AU_RESPONSE_CODE')
        BEGIN
            DROP SYNONYM AU_RESPONSE_CODE;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].AU_RESPONSE_CODE FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].AU_RESPONSE_CODE';
    EXEC sp_sqlexec @SQL;

    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'AUI_DEBIT_GENERAL_ACCOUNT')
        BEGIN
            DROP SYNONYM AUI_DEBIT_GENERAL_ACCOUNT;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].AUI_DEBIT_GENERAL_ACCOUNT FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].AUI_DEBIT_GENERAL_ACCOUNT';
    EXEC sp_sqlexec @SQL;

    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'AUI_GENERAL_ACC_AVAILABLE_H')
        BEGIN
            DROP SYNONYM AUI_GENERAL_ACC_AVAILABLE_H;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].AUI_GENERAL_ACC_AVAILABLE_H FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].AUI_GENERAL_ACC_AVAILABLE_H';
    EXEC sp_sqlexec @SQL;

    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'AUI_PAYMENT_MEDIA')
        BEGIN
            DROP SYNONYM AUI_PAYMENT_MEDIA;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].AUI_PAYMENT_MEDIA FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].AUI_PAYMENT_MEDIA';
    EXEC sp_sqlexec @SQL;


    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'AU_BRAND')
        BEGIN
            DROP SYNONYM AU_BRAND;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].AU_BRAND FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].AU_BRAND';
    EXEC sp_sqlexec @SQL;

    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'T_CURRENCY')
        BEGIN
            DROP SYNONYM T_CURRENCY;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].T_CURRENCY FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].T_CURRENCY';
    EXEC sp_sqlexec @SQL;

    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'AUI_GENERAL_ACCOUNT')
        BEGIN
            DROP SYNONYM AUI_GENERAL_ACCOUNT;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].AUI_GENERAL_ACCOUNT FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].AUI_GENERAL_ACCOUNT';
    EXEC sp_sqlexec @SQL;

    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'AUI_AFFINITY_GROUP')
        BEGIN
            DROP SYNONYM AUI_AFFINITY_GROUP;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].AUI_AFFINITY_GROUP FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].AUI_AFFINITY_GROUP';
    EXEC sp_sqlexec @SQL;

    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'AUI_ACCOUNT_RELATION')
        BEGIN
            DROP SYNONYM AUI_ACCOUNT_RELATION;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].AUI_ACCOUNT_RELATION FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].AUI_ACCOUNT_RELATION';
    EXEC sp_sqlexec @SQL;


    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'AU_TRANSACTION_LOG')
        BEGIN
            DROP SYNONYM AU_TRANSACTION_LOG;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].AU_TRANSACTION_LOG FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].AU_TRANSACTION_LOG';
    EXEC sp_sqlexec @SQL;


    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'AUI_ACCOUNT_STATUS')
        BEGIN
            DROP SYNONYM AUI_ACCOUNT_STATUS;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].AUI_ACCOUNT_STATUS FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].AUI_ACCOUNT_STATUS';
    EXEC sp_sqlexec @SQL;


    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'AUI_BUSINESS_DATE')
        BEGIN
            DROP SYNONYM AUI_BUSINESS_DATE;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].AUI_BUSINESS_DATE FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].AUI_BUSINESS_DATE';
    EXEC sp_sqlexec @SQL;

    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'AUI_CREDIT_LINE_DEFINITION_T')
        BEGIN
            DROP SYNONYM AUI_CREDIT_LINE_DEFINITION_T;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].AUI_CREDIT_LINE_DEFINITION_T FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].AUI_CREDIT_LINE_DEFINITION_T';
    EXEC sp_sqlexec @SQL;

    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'AUI_ISSUER')
        BEGIN
            DROP SYNONYM AUI_ISSUER;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].AUI_ISSUER FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].AUI_ISSUER';
    EXEC sp_sqlexec @SQL;

    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'AUI_ISSUER_CREDIT_LINE')
        BEGIN
            DROP SYNONYM AUI_ISSUER_CREDIT_LINE;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].AUI_ISSUER_CREDIT_LINE FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].AUI_ISSUER_CREDIT_LINE';
    EXEC sp_sqlexec @SQL;

    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'AUI_ISSUER_CURRENCY')
        BEGIN
            DROP SYNONYM AUI_ISSUER_CURRENCY;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].AUI_ISSUER_CURRENCY FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].AUI_ISSUER_CURRENCY';
    EXEC sp_sqlexec @SQL;

    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'AUI_ISSUER_EMV_KEY')
        BEGIN
            DROP SYNONYM AUI_ISSUER_EMV_KEY;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].AUI_ISSUER_EMV_KEY FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].AUI_ISSUER_EMV_KEY';
    EXEC sp_sqlexec @SQL;

    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'AUI_ISSUER_KEY')
        BEGIN
            DROP SYNONYM AUI_ISSUER_KEY;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].AUI_ISSUER_KEY FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].AUI_ISSUER_KEY';
    EXEC sp_sqlexec @SQL;

    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'AUI_ISSUER_MEDIA_SUPPORT_TYPE')
        BEGIN
            DROP SYNONYM AUI_ISSUER_MEDIA_SUPPORT_TYPE;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].AUI_ISSUER_MEDIA_SUPPORT_TYPE FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].AUI_ISSUER_MEDIA_SUPPORT_TYPE';
    EXEC sp_sqlexec @SQL;

    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'AUI_ISSUER_PRODUCT')
        BEGIN
            DROP SYNONYM AUI_ISSUER_PRODUCT;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].AUI_ISSUER_PRODUCT FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].AUI_ISSUER_PRODUCT';
    EXEC sp_sqlexec @SQL;

    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'AUI_ISSUER_PRODUCT_CREDIT_LINE')
        BEGIN
            DROP SYNONYM AUI_ISSUER_PRODUCT_CREDIT_LINE;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].AUI_ISSUER_PRODUCT_CREDIT_LINE FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].AUI_ISSUER_PRODUCT_CREDIT_LINE';
    EXEC sp_sqlexec @SQL;

    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'AUI_ISSUER_PRODUCT_VALIDATION')
        BEGIN
            DROP SYNONYM AUI_ISSUER_PRODUCT_VALIDATION;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].AUI_ISSUER_PRODUCT_VALIDATION FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].AUI_ISSUER_PRODUCT_VALIDATION';
    EXEC sp_sqlexec @SQL;

    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'AUI_OVERDRAFT')
        BEGIN
            DROP SYNONYM AUI_OVERDRAFT;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].AUI_OVERDRAFT FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].AUI_OVERDRAFT';
    EXEC sp_sqlexec @SQL;

    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'AUI_PACKAGE_FEE')
        BEGIN
            DROP SYNONYM AUI_PACKAGE_FEE;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].AUI_PACKAGE_FEE FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].AUI_PACKAGE_FEE';
    EXEC sp_sqlexec @SQL;

    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'AUI_RATE_VALUE')
        BEGIN
            DROP SYNONYM AUI_RATE_VALUE;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].AUI_RATE_VALUE FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].AUI_RATE_VALUE';
    EXEC sp_sqlexec @SQL;

    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'AUI_RATE')
        BEGIN
            DROP SYNONYM AUI_RATE;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].AUI_RATE FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].AUI_RATE';
    EXEC sp_sqlexec @SQL;

    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'AUI_SALE_PLAN')
        BEGIN
            DROP SYNONYM AUI_SALE_PLAN;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].AUI_SALE_PLAN FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].AUI_SALE_PLAN';
    EXEC sp_sqlexec @SQL;

    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'AUI_SERVICE_CODE')
        BEGIN
            DROP SYNONYM AUI_SERVICE_CODE;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].AUI_SERVICE_CODE FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].AUI_SERVICE_CODE';
    EXEC sp_sqlexec @SQL;

    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'T_HOLIDAY_CALENDAR')
        BEGIN
            DROP SYNONYM T_HOLIDAY_CALENDAR;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].T_HOLIDAY_CALENDAR FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].T_HOLIDAY_CALENDAR';
    EXEC sp_sqlexec @SQL;

    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'AUI_PREPAID_GENERAL_ACCOUNT')
        BEGIN
            DROP SYNONYM AUI_PREPAID_GENERAL_ACCOUNT;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].AUI_PREPAID_GENERAL_ACCOUNT FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].AUI_PREPAID_GENERAL_ACCOUNT';
    EXEC sp_sqlexec @SQL;

    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'AUI_PRODUCT_CREDIT_LINE_DEF_T')
        BEGIN
            DROP SYNONYM AUI_PRODUCT_CREDIT_LINE_DEF_T;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].AUI_PRODUCT_CREDIT_LINE_DEF_T FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].AUI_PRODUCT_CREDIT_LINE_DEF_T';
    EXEC sp_sqlexec @SQL;

    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'AUI_OPEN_TOKENIZATION')
        BEGIN
            DROP SYNONYM AUI_OPEN_TOKENIZATION;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].AUI_OPEN_TOKENIZATION FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].AUI_OPEN_TOKENIZATION';
    EXEC sp_sqlexec @SQL;

    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'AUI_EXCHANGE_RATE')
        BEGIN
            DROP SYNONYM AUI_EXCHANGE_RATE;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].AUI_EXCHANGE_RATE FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].AUI_EXCHANGE_RATE';
    EXEC sp_sqlexec @SQL;

    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'AUI_PAYMENT_MEDIA_PIN_CHANGE_H')
        BEGIN
            DROP SYNONYM AUI_PAYMENT_MEDIA_PIN_CHANGE_H;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].AUI_PAYMENT_MEDIA_PIN_CHANGE_H FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].AUI_PAYMENT_MEDIA_PIN_CHANGE_H';
    EXEC sp_sqlexec @SQL;


    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'AU_MCC')
        BEGIN
            DROP SYNONYM AU_MCC;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].AU_MCC FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].AU_MCC';
    EXEC sp_sqlexec @SQL;

    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'AU_OPEN_TRANSACTION_ADD_INFO')
        BEGIN
            DROP SYNONYM AU_OPEN_TRANSACTION_ADD_INFO;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].AU_OPEN_TRANSACTION_ADD_INFO FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].AU_OPEN_TRANSACTION_ADD_INFO';
    EXEC sp_sqlexec @SQL;

    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'AU_OPEN_TRX_EXTERNAL_CHANNEL')
        BEGIN
            DROP SYNONYM AU_OPEN_TRX_EXTERNAL_CHANNEL;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].AU_OPEN_TRX_EXTERNAL_CHANNEL FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].AU_OPEN_TRX_EXTERNAL_CHANNEL';
    EXEC sp_sqlexec @SQL;

    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'AU_TRANSACTION_STATUS')
        BEGIN
            DROP SYNONYM AU_TRANSACTION_STATUS;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].AU_TRANSACTION_STATUS FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].AU_TRANSACTION_STATUS';
    EXEC sp_sqlexec @SQL;

    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'AUI_CREDIT_LINE_DEF_T')
        BEGIN
            DROP SYNONYM AUI_CREDIT_LINE_DEF_T;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].AUI_CREDIT_LINE_DEF_T FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].AUI_CREDIT_LINE_DEF_T';
    EXEC sp_sqlexec @SQL;

    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'AUI_CREDIT_LINE_DETERM_DATA')
        BEGIN
            DROP SYNONYM AUI_CREDIT_LINE_DETERM_DATA;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].AUI_CREDIT_LINE_DETERM_DATA FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].AUI_CREDIT_LINE_DETERM_DATA';
    EXEC sp_sqlexec @SQL;

    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'AUI_CUSTOMER')
        BEGIN
            DROP SYNONYM AUI_CUSTOMER;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].AUI_CUSTOMER FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].AUI_CUSTOMER';
    EXEC sp_sqlexec @SQL;

    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'AUI_EMV_PINBLOCK')
        BEGIN
            DROP SYNONYM AUI_EMV_PINBLOCK;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].AUI_EMV_PINBLOCK FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].AUI_EMV_PINBLOCK';
    EXEC sp_sqlexec @SQL;

    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'AUI_EMV_SCRIPT_UPDATE_STATUS')
        BEGIN
            DROP SYNONYM AUI_EMV_SCRIPT_UPDATE_STATUS;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].AUI_EMV_SCRIPT_UPDATE_STATUS FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].AUI_EMV_SCRIPT_UPDATE_STATUS';
    EXEC sp_sqlexec @SQL;

    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'AUI_FINANCIAL_RELATION')
        BEGIN
            DROP SYNONYM AUI_FINANCIAL_RELATION;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].AUI_FINANCIAL_RELATION FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].AUI_FINANCIAL_RELATION';
    EXEC sp_sqlexec @SQL;

    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'AUI_GENERAL_ACC_CRED_LINE_H')
        BEGIN
            DROP SYNONYM AUI_GENERAL_ACC_CRED_LINE_H;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].AUI_GENERAL_ACC_CRED_LINE_H FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].AUI_GENERAL_ACC_CRED_LINE_H';
    EXEC sp_sqlexec @SQL;

    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'AUI_ISSUER_PARAMETER')
        BEGIN
            DROP SYNONYM AUI_ISSUER_PARAMETER;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].AUI_ISSUER_PARAMETER FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].AUI_ISSUER_PARAMETER';
    EXEC sp_sqlexec @SQL;

    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'AUI_MEDIA_SUPPORT_TYPE')
        BEGIN
            DROP SYNONYM AUI_MEDIA_SUPPORT_TYPE;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].AUI_MEDIA_SUPPORT_TYPE FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].AUI_MEDIA_SUPPORT_TYPE';
    EXEC sp_sqlexec @SQL;

    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'AUI_REWARDS_GENERAL_ACCOUNT')
        BEGIN
            DROP SYNONYM AUI_REWARDS_GENERAL_ACCOUNT;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].AUI_REWARDS_GENERAL_ACCOUNT FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].AUI_REWARDS_GENERAL_ACCOUNT';
    EXEC sp_sqlexec @SQL;

    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'AUI_SYNCH_QUEUE')
        BEGIN
            DROP SYNONYM AUI_SYNCH_QUEUE;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].AUI_SYNCH_QUEUE FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].AUI_SYNCH_QUEUE';
    EXEC sp_sqlexec @SQL;

    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'AUI_SYNCH_STATUS_TRANSITION')
        BEGIN
            DROP SYNONYM AUI_SYNCH_STATUS_TRANSITION;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].AUI_SYNCH_STATUS_TRANSITION FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].AUI_SYNCH_STATUS_TRANSITION';
    EXEC sp_sqlexec @SQL;

    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'AUI_TRANSACTION_LIFETIME')
        BEGIN
            DROP SYNONYM AUI_TRANSACTION_LIFETIME;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].AUI_TRANSACTION_LIFETIME FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].AUI_TRANSACTION_LIFETIME';
    EXEC sp_sqlexec @SQL;

    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'T_CITY')
        BEGIN
            DROP SYNONYM T_CITY;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].T_CITY FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].T_CITY';
    EXEC sp_sqlexec @SQL;

    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'T_COUNTRY')
        BEGIN
            DROP SYNONYM T_COUNTRY;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].T_COUNTRY FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].T_COUNTRY';
    EXEC sp_sqlexec @SQL;

    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'T_DOCUMENT_TYPE')
        BEGIN
            DROP SYNONYM T_DOCUMENT_TYPE;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].T_DOCUMENT_TYPE FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].T_DOCUMENT_TYPE';
    EXEC sp_sqlexec @SQL;

    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'T_GEO_STATE')
        BEGIN
            DROP SYNONYM T_GEO_STATE;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].T_GEO_STATE FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].T_GEO_STATE';
    EXEC sp_sqlexec @SQL;

    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'T_HOLIDAY_CALENDAR')
        BEGIN
            DROP SYNONYM T_HOLIDAY_CALENDAR;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].T_HOLIDAY_CALENDAR FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].T_HOLIDAY_CALENDAR';
    EXEC sp_sqlexec @SQL;

    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'T_LMK')
        BEGIN
            DROP SYNONYM T_LMK;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].T_LMK FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].T_LMK';
    EXEC sp_sqlexec @SQL;

    IF EXISTS(SELECT * FROM  sys.synonyms s WHERE s.name = 'AT_HOLIDAY_CALENDAR')
        BEGIN
            DROP SYNONYM AT_HOLIDAY_CALENDAR;
        END
    SELECT @SQL = 'CREATE SYNONYM [dbo].AT_HOLIDAY_CALENDAR FOR '+ 'EVTC_AAS_PAYE_PR' +'.[dbo].AT_HOLIDAY_CALENDAR';
    EXEC sp_sqlexec @SQL;
END
GO