SELECT
    TOT.CHARGED_AMOUNT AuthorizedAmount,
    TOT.LOCAL_DATE LocalDate,
    TOT.AUTHORIZATION_CODE AuthorizationCode,

    TOT.TRANSACTION_COUNTRY_CODE CountryCode,
    TCOUNTRY.ID_COUNTRY IdCountry,
    TCOUNTRY.COUNTRY_NAME CountryName,
    TCOUNTRYTRANSACTION.COUNTRY_NAME TransactionCountryName,
    TOT.TRANSACTION_GEO_STATE_NAME GeoStateName,
    TOT.TRANSACTION_CITY_NAME CityName,
    TOT.ID_TRANSACTION IdTransaction,
    TOT.TRANSACTION_PAN TransactionPan,
    PROD.ID_PRODUCT IdProduct,
    PROD.PRODUCT_NAME ProductName,
    PROD.ID_BRAND IdBrand,
    BRAND.NAME BrandName,
    TOT.MCC_CODE IdMcc,
    MCC.DESCRIPTION MccDescription,
    TOT.ACQUIRING_INSTITUTION_CODE AcquiringInstitutionCode,
    TOT.POS_CONDITION_CODE POSConditionCode,
    TID.ID_SALE_PLAN IdSalePlan,
    TOT.MCC_CODE MccCode,
    TOT.EXPIRATION_DATE ExpirationDate,
    TOT.PAN_SEQUENCE_NUMBER PaymentMedSequenceNumber,
    TRXSTA.DESCRIPTION TransactionStatusDescription,
    TRXSTA.ID_TRANSACTION_STATUS IdTransactionStatus,
    TOT.MTI_CODE MTI,
    TOT.PROCESSING_CODE ProcessingCode,
    TOT.MESSAGE_AMNT MessageAmount,
    TOT.ORIGINAL_MESSAGE_AMNT OriginalMessageAmount,
    TOT.MESSAGE_CURRENCY_CODE MessageCurrencyCode,
    TOT.CARD_BILLING_AMNT CBAmount,
    TOT.CARD_BILLING_CURRENCY_CODE CBCurrencyCode,
    TOT.TRANSACTION_DATE TransactionDate,
    TOT.ID_RESPONSE_CODE IdResponseCode,
    RESCOD.DESCRIPTION ResponseCode,
    TOT.RRN RNN,
    TOT.CARD_ACCEPTOR_NAME MerchantName,
    TOT.CARD_ACCEPTOR_CODE CardAcceptorCode,
    TOT.CARD_ACCEPTOR_TERMINAL_CODE CardAcceptorTerminalCode,
    TOT.EXTERNAL_TRACE_NUMBER_CODE ExternalTraceNumberCode,
    TOT.FORWARDING_INSTITUTION_CODE ForwardingInstitutionCode,
    TOT.POS_ENTRY_MODE PosEntryMode,
    CURR.DECIMAL_DIGITS AS MessageCurrencyDecimalDig,
    CURR.DISPLAY_SYMBOL AS MessageCurrencyDisplaySymbol,
    CBCURR.DECIMAL_DIGITS AS CBCurrencyDecimalDig,
    CBCURR.DISPLAY_SYMBOL AS CBCurrencyDisplaySymbol,
    TOT.TRANSACTION_TYPE TransactionType,
    TID.ID_ISSUER IdIssuer,
    TID.CONFIRMATION_DATE ConfirmationDate,
    PM.ID_PAYMENT_MEDIA IdPaymentMedia,
    PM.EXPIRATION_DATE PaymentMediaDueDate,
    SPLAN.NAME SalePlanName,
    SPLAN.INSTALLMENT_QUANTITY InstallmentQuantity,
    TID.OVERDRAFT_AMOUNT OverdraftAmount,
    TOT.TRANSACTION_MASKED_PAN TransactionMaskedPan,
    TOT.TRANSACTION_CATEGORY TransactionCategory,
    TOT.CASHBACK Cashback,
    TOT.TIP_AMOUNT TipAmount,
    TOT.FEE_AMOUNT FeeAmount,
    SPLAN.TYPE SalePlanType,
    TOT.TRANSACTION_BEGIN_TIME TransactionBeginTime,
    TOT.TERMINAL_ENTRY_CAPABILITY TerminalEntryCapability,
    TOT.ID_MESSAGE_CHANNEL IdChannelMessage,
    GA.ID_GENERAL_ACCOUNT IdGeneralAccount,
    PM.EXTERNAL_NAME CardHolderName,
    '' CardHolderSurname,
    CUSTOMER.DOCUMENT_NUMBER CardHolderDocumentNumber,
    '' GeneralAccountCycle,
    accStatus.DESCRIPTION GeneralAccountStatus,
    GA.INTERNAL_ACCOUNT_NUMBER GeneralAccountNumber,
    '' AccDebitCtrlPenalty,
    TOT.TRANSACTION_BIN TransactionBin,
    ip.EXTERNAL_ISSUER_ID ProductCode,
    TOT.TRANSACTION_PAN Token,
    TOT.IS_SMS IsSms,
    TOT.INSTALLMENT_SEQUENCE_COUNT InstallmentSequenceCount,
    TOT.INSTALLMENT_SEQUENCE_NUMBER InstallmentSequenceNumber,
    TOT.FINAL_AUTHORIZATION_INDICATOR FinalAuthorizationIndicator,
    currencyAuthorized.DISPLAY_SYMBOL AuthorizedCurrencySymbol,
    currencyAuthorized.DECIMAL_DIGITS AuthorizedDecimalDigits,

    CASE
        WHEN TID.IS_PARTIAL_AUTHORIZATION = 1 THEN 'YES'
        WHEN TID.IS_PARTIAL_AUTHORIZATION = 0 THEN 'NO'
        WHEN TID.IS_PARTIAL_AUTHORIZATION IS NULL AND TOT.CARD_BILLING_AMNT > TOT.CHARGED_AMOUNT AND TOT.CHARGED_AMOUNT > 0  THEN 'YES'
        ELSE 'NO'
        END AuthorizedApplyPartial,
    CASE
        WHEN auiOpenToken.ID_TRANSACTION IS NULL THEN 'NO'
        ELSE 'YES'
        END IsTokenized,
    COALESCE(PROD.PRODUCT_TYPE, (SELECT PRODUCT_TYPE FROM AUI_PRODUCT WHERE ID_PRODUCT = TID.ID_PRODUCT), 1) AS PRODUCT_TYPE
FROM
    AU_OPEN_TRANSACTION TOT
        INNER JOIN T_CURRENCY CURR ON CURR.DEFAULT_NUMERIC_CODE = TOT.MESSAGE_CURRENCY_CODE
        INNER JOIN AU_TRANSACTION_STATUS TRXSTA ON TRXSTA.ID_TRANSACTION_STATUS = TOT.ID_TRANSACTION_STATUS
        INNER JOIN AUI_TRX_ISSUER_DATA TID ON TID.ID_TRANSACTION = TOT.ID_TRANSACTION
        LEFT OUTER JOIN T_CURRENCY CBCURR ON CBCURR.DEFAULT_NUMERIC_CODE = TOT.CARD_BILLING_CURRENCY_CODE
        LEFT OUTER JOIN AUI_PAYMENT_MEDIA PM ON PM.ID_PAYMENT_MEDIA =  TID.ID_PAYMENT_MEDIA
        LEFT OUTER JOIN AUI_PAYMENT_MEDIA_RELATION PMR ON PMR.ID_PAYMENT_MEDIA = PM.ID_PAYMENT_MEDIA
        LEFT OUTER JOIN AUI_ACCOUNT_RELATION AR ON PMR.ID_ACCOUNT_RELATION = AR.ID_ACCOUNT_RELATION
        LEFT OUTER JOIN AUI_FINANCIAL_RELATION FR ON AR.ID_FINANCIAL_RELATION = FR.ID_FINANCIAL_RELATION
        LEFT OUTER JOIN AUI_GENERAL_ACCOUNT GA ON GA.ID_GENERAL_ACCOUNT = FR.ID_GENERAL_ACCOUNT
        LEFT OUTER JOIN AU_MCC MCC ON MCC.ID_MCC = TOT.MCC_CODE
        LEFT OUTER JOIN AU_RESPONSE_CODE RESCOD ON RESCOD.ID_RESPONSE_CODE = TOT.ID_RESPONSE_CODE
        LEFT OUTER JOIN AUI_PRODUCT PROD ON PROD.ID_PRODUCT = PM.ID_PRODUCT
        LEFT OUTER JOIN AU_BRAND BRAND ON BRAND.ID_BRAND = PROD.ID_BRAND
        LEFT OUTER JOIN T_COUNTRY TCOUNTRY ON TCOUNTRY.NUMERIC_CODE = TOT.ACQUIRER_COUNTRY_CODE
        LEFT OUTER JOIN T_COUNTRY TCOUNTRYTRANSACTION ON (TCOUNTRYTRANSACTION.ISO_CODE = TOT.TRANSACTION_COUNTRY_CODE OR TCOUNTRYTRANSACTION.CHAR_CODE = TOT.TRANSACTION_COUNTRY_CODE)
        LEFT OUTER JOIN AUI_SALE_PLAN SPLAN ON SPLAN.ID_SALE_PLAN = TID.ID_SALE_PLAN
        LEFT OUTER JOIN AUI_CUSTOMER CUSTOMER ON CUSTOMER.ID_CUSTOMER = FR.ID_CUSTOMER
        LEFT OUTER JOIN AUI_ACCOUNT_STATUS accStatus ON accStatus.ID_ACCOUNT_STATUS = GA.ID_ACCOUNT_STATUS
        LEFT OUTER JOIN AUI_ISSUER_PRODUCT ip ON ip.ID_ISSUER = TID.ID_ISSUER AND ip.ID_PRODUCT = PROD.ID_PRODUCT
        LEFT OUTER JOIN T_CURRENCY currencyAuthorized ON TOT.CARD_BILLING_CURRENCY_CODE = currencyAuthorized.ID_CURRENCY
        LEFT JOIN AUI_OPEN_TOKENIZATION auiOpenToken ON auiOpenToken.ID_TRANSACTION = TOT.ID_TRANSACTION
--where     TOT.CHARGED_AMOUNT > 0

WHERE

   (TID.ID_ISSUER = 100)
and      TOT.CHARGED_AMOUNT > 0
  --AND TOT.LOCAL_DATE >= '2025-10-01 00:00:00'
  --AND TOT.LOCAL_DATE <= '2025-10-05 23:59:59'
--   AND GA.ID_GENERAL_ACCOUNT = :IdAccount
--   AND PROD.ID_PRODUCT = :IdProduct
--   AND PM.ID_PAYMENT_MEDIA = :IdPaymentMedia
--   AND TOT.MTI_CODE = :MTI
--   AND TOT.MESSAGE_AMNT = :TransactionAmount
--   AND TID.ID_TRX_EXPORT_STATUS = :IdTrxExportStatus
  --AND (UPPER(TOT.CARD_ACCEPTOR_NAME) LIKE  LTRIM(RTRIM(UPPER('%' || :MerchantName  || '%'))))
--   AND TOT.ID_TRANSACTION_STATUS in :IdTrxStatus
--   AND TRXSTA.ID_TRANSACTION_STATUS not in :RejectedStatus
--   AND TOT.TRANSACTION_CATEGORY = :TxCategory
--   AND TOT.TRANSACTION_TYPE = :TxType
--   and TOT.AUTHORIZATION_CODE = :AuthorizationCode
--   and TOT.TRANSACTION_IDENTIFIER = :TransactionIdentifier
--   AND TOT.ID_RESPONSE_CODE = :IdResponseCode
--   AND PROD.PRODUCT_TYPE = :AccountType
--   AND CUSTOMER.ID_DOCUMENT_TYPE = :IdDocumentType
--   AND CUSTOMER.DOCUMENT_NUMBER = :DocumentNumber
--   AND TOT.TRANSACTION_MASKED_PAN = :MaskedPan
--   AND GA.INTERNAL_ACCOUNT_NUMBER = :InternalAccountNumber
--   AND (GA.INTERNAL_ACCOUNT_NUMBER = :PaddedInternalAccountNumber OR GA.INTERNAL_ACCOUNT_NUMBER = :NonPaddedInternalAccountNumber)
--   AND TOT.POS_ENTRY_MODE = :PosEntryMode
--   AND BRAND.ID_BRAND = :Brand
ORDER BY TOT.LOCAL_DATE desc