INSERT INTO C_PARAMETER (ID_PARAMETER, PARAMETER_NAME, CODE, VALUE_TYPE, PARAMETER_TYPE, MODULE,
                         IS_CONFIGURED_BY_SCREEN)
VALUES ((SELECT MAX(ID_PARAMETER) + 1 FROM C_PARAMETER), 'Habilita 2da linea para Embossing de la Empresa',
        'EMBOSSING_COMPANY_NAME', 4, 6, 'ICS', 0);

INSERT INTO IBC_ISSUER_PRODUCT_PARAMETER
VALUES ((SELECT ID_PARAMETER FROM C_PARAMETER WHERE CODE = 'EMBOSSING_COMPANY_NAME'),
        641,
        (SELECT ip.ID_PRODUCT
         FROM IBC_ISSUER_PRODUCT ip
                  INNER JOIN IBC_PRODUCT p ON p.ID_PRODUCT = ip.ID_PRODUCT
         WHERE ip.ID_ISSUER = 641
           AND p.PRODUCT_NAME LIKE 'MC Business - Cr%'),
        '2026-01-01 00:00:00.000', NULL, NULL, NULL, NULL, 1);

-- ROLLBACK

DELETE
FROM IBC_ISSUER_PRODUCT_PARAMETER
WHERE ID_PARAMETER = (SELECT ID_PARAMETER FROM C_PARAMETER WHERE CODE = 'EMBOSSING_COMPANY_NAME')
  AND ID_ISSUER = 641
  AND ID_PRODUCT = (SELECT ip.ID_PRODUCT
                    FROM IBC_ISSUER_PRODUCT ip
                             INNER JOIN IBC_PRODUCT p ON p.ID_PRODUCT = ip.ID_PRODUCT
                    WHERE ip.ID_ISSUER = 641
                      AND p.PRODUCT_NAME LIKE 'MC Business - Cr%');

DELETE
FROM C_PARAMETER
WHERE CODE = 'EMBOSSING_COMPANY_NAME';

-- Valida INSERT en C_PARAMETER
SELECT '1' CANTIDAD_REGISTROS_MAYOR_O_IGUAL, COUNT(*) CANT_REGISTRO_REAL
FROM C_PARAMETER
WHERE CODE = 'EMBOSSING_COMPANY_NAME';

-- Valida INSERT en IBC_ISSUER_PRODUCT_PARAMETER
SELECT '1' CANTIDAD_REGISTROS_MAYOR_O_IGUAL, COUNT(*) CANT_REGISTRO_REAL
FROM IBC_ISSUER_PRODUCT_PARAMETER
WHERE ID_PARAMETER = (SELECT ID_PARAMETER FROM C_PARAMETER WHERE CODE = 'EMBOSSING_COMPANY_NAME')
  AND ID_ISSUER = 641
  AND ID_PRODUCT = (SELECT ip.ID_PRODUCT
                    FROM IBC_ISSUER_PRODUCT ip
                             INNER JOIN IBC_PRODUCT p ON p.ID_PRODUCT = ip.ID_PRODUCT
                    WHERE ip.ID_ISSUER = 641
                      AND p.PRODUCT_NAME LIKE 'MC Business - Cr%');


----
-- Nueva Tabla para almacencer la información del EmbossingCompanyName en lugar de crear una columna la tabla PHYSICAL_PERSON o ICS_CUSTOMER

-- Crear tabla ICS_CUSTOMER_BUSINESS_ADDITIONAL_INFO
IF NOT EXISTS (SELECT 1
               FROM sys.tables
               WHERE object_id = OBJECT_ID('dbo.ICS_CUSTOMER_BUSINESS_ADDITIONAL_INFO'))
    BEGIN
        CREATE TABLE dbo.ICS_CUSTOMER_BUSINESS_ADDITIONAL_INFO
        (
            ID_CUSTOMER            INT         NOT NULL,
            EMBOSSING_COMPANY_NAME VARCHAR(40) NOT NULL,
            CONSTRAINT PK_ICS_CUSTOMER_BUSINESS_ADDITIONAL_INFO
                PRIMARY KEY (ID_CUSTOMER),
            CONSTRAINT FK_ICS_CUSTOMER_BUSINESS_ADDITIONAL_INFO_CUSTOMER
                FOREIGN KEY (ID_CUSTOMER)
                    REFERENCES dbo.ICS_CUSTOMER (ID_CUSTOMER)
        );
    END

-- ROLLBACK
IF EXISTS (SELECT 1
           FROM sys.tables
           WHERE object_id = OBJECT_ID('dbo.ICS_CUSTOMER_BUSINESS_ADDITIONAL_INFO'))
    BEGIN
        DROP TABLE dbo.ICS_CUSTOMER_BUSINESS_ADDITIONAL_INFO;
    END

-- Validar que la tabla se haya creado correctamente
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ICS_CUSTOMER_BUSINESS_ADDITIONAL_INFO';


-- BEFORE SQL:
SELECT COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ICS_CUSTOMER_BUSINESS_ADDITIONAL_INFO'
  AND COLUMN_NAME = 'EMBOSSING_COMPANY_NAME';

-- AFTER SQL:
SELECT TABLE_NAME, COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ICS_CUSTOMER_BUSINESS_ADDITIONAL_INFO'
  AND COLUMN_NAME = 'EMBOSSING_COMPANY_NAME'

select *
from DATABASECHANGELOG
order by ORDEREXECUTED desc

-- Validar que la columna se haya creado correctamente
SELECT 1
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ICS_CUSTOMER'
  AND COLUMN_NAME = 'EMBOSSING_COMPANY_NAME';

SELECT COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ICS_CUSTOMER'
  AND COLUMN_NAME = 'EMBOSSING_COMPANY_NAME';

SELECT TABLE_NAME, COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ICS_CUSTOMER'
  AND COLUMN_NAME = 'EMBOSSING_COMPANY_NAME';

-- Ver ultimas cuentas creadas
select ga.ID_GENERAL_ACCOUNT, ga.INTERNAL_ACCOUNT_NUMBER, icb.ID_CUSTOMER, icb.EMBOSSING_COMPANY_NAME, ga.*, c.*
from IAC_GENERAL_ACCOUNT ga
         INNER JOIN IBC_PRODUCT p on p.ID_PRODUCT = ga.ID_MAIN_PRODUCT
         inner join ICS_FINANCIAL_RELATION fr on fr.ID_GENERAL_ACCOUNT = ga.ID_GENERAL_ACCOUNT
         inner join ICS_CUSTOMER c on c.ID_CUSTOMER = fr.ID_CUSTOMER
left join ICS_CUSTOMER_BUSINESS_ADDITIONAL_INFO icb on icb.ID_CUSTOMER = c.ID_CUSTOMER
--WHERE ga.ID_ISSUER = 641 and ga.ID_GENERAL_ACCOUNT = 265
order by ga.ID_GENERAL_ACCOUNT desc

select * from ICS_CUSTOMER_BUSINESS_ADDITIONAL_INFO

SELECT
    TODAY_DATE TodayDate
FROM IBC_BUSINESS_DATE
WHERE ID_ISSUER = 641;

UPDATE AUI_PAYMENT_MEDIA SET
                             FIRST_NAME = 'test2',
                             MIDDLE_NAME = '',
                             LAST_NAME = 'test2',
                             SECOND_LAST_NAME = ''
WHERE ID_PAYMENT_MEDIA in (
    SELECT
        pMedia.ID_PAYMENT_MEDIA
    FROM IAC_PAYMENT_MEDIA pMedia
             INNER JOIN ICS_PAYMENT_MEDIA_RELATION pmRel ON pmRel.ID_PAYMENT_MEDIA = pMedia.ID_PAYMENT_MEDIA
             INNER JOIN ICS_ACCOUNT_RELATION accRel ON accRel.ID_ACCOUNT_RELATION = pmRel.ID_ACCOUNT_RELATION
             INNER JOIN ICS_FINANCIAL_RELATION finRelMain ON finRelMain.ID_FINANCIAL_RELATION = accRel.ID_FINANCIAL_RELATION
             INNER JOIN ICS_CUSTOMER mainCustomer ON finRelMain.ID_CUSTOMER = mainCustomer.ID_CUSTOMER
             INNER JOIN IAC_GENERAL_ACCOUNT gralAcc ON gralAcc.ID_GENERAL_ACCOUNT = finRelMain.ID_GENERAL_ACCOUNT
    WHERE mainCustomer.ID_CUSTOMER = 448
)

CREATE TABLE dbo.ICS_CUSTOMER_BUSINESS_ADDITIONAL_INFO
(
    ID_CUSTOMER            INT         NOT NULL,
    EMBOSSING_COMPANY_NAME VARCHAR(40) NOT NULL,
    CONSTRAINT PK_ICS_CUSTOMER_BUSINESS_ADDITIONAL_INFO
        PRIMARY KEY (ID_CUSTOMER),
    CONSTRAINT FK_ICS_CUSTOMER_BUSINESS_ADDITIONAL_INFO_CUSTOMER
        FOREIGN KEY (ID_CUSTOMER)
            REFERENCES dbo.ICS_CUSTOMER (ID_CUSTOMER)
);

-- querty taruman para recuperar la info
SELECT cus.ID_ISSUER              AS IdIssuer,
       cus.ID_DOCUMENT_TYPE       AS IdDocumentType,
       cus.DOCUMENT               AS Document,
       cus.EMBOSSING_NAME         AS EmbossingName,
       icb.EMBOSSING_COMPANY_NAME AS EmbossingCompanyName,
       cus.CUSTOMER_TYPE          AS CustomerType,
       docType.DESCRIPTION        AS DocumentTypeDesc,
       docType.MASK               AS DocumentTypeMask,
       cus.ID_CUSTOMER            AS IdCustomer,
       cus.IS_INNOMINATE          AS IsInnominate,
       cus.EXTERNAL_CUSTOMER_ID   AS ExternalCustomerId,
       cus.ID_CUSTOMER_CATEGORY   AS IdCustomerCategory,
       cus.DOCUMENT_EMISSION_DATE AS DocumentEmissionDate,
       cus.DOCUMENT_DUE_DATE      AS DocumentDueDate
FROM ICS_CUSTOMER cus
         INNER JOIN
     TGD_DOCUMENT_TYPE docType ON cus.ID_DOCUMENT_TYPE = docType.ID_DOCUMENT_TYPE
         LEFT JOIN ICS_CUSTOMER_BUSINESS_ADDITIONAL_INFO icb on icb.ID_CUSTOMER = cus.ID_CUSTOMER

select * from ICS_CUSTOMER_BUSINESS_ADDITIONAL_INFO