--------
-- SQL
--------
ALTER TABLE IAC_ACCOUNT_SETT_MODEL
    ADD ID_ISS_SETT_MOD_TYPE BIGINT NULL;

ALTER TABLE IAC_ACCOUNT_SETT_MODEL
    ADD CONSTRAINT FK_IAC_ACCSM_REFERENCE_IBC_ISMT
        FOREIGN KEY (ID_ISS_SETT_MOD_TYPE)
            REFERENCES IBC_ISSUER_SETT_MODEL_TYPE (ID_ISS_SETT_MOD_TYPE);


-------------------------
-- ROLLBACK
-------------------------
ALTER TABLE IAC_ACCOUNT_SETT_MODEL
    DROP CONSTRAINT FK_IAC_ACCSM_REFERENCE_IBC_ISMT;

ALTER TABLE IAC_ACCOUNT_SETT_MODEL
    DROP COLUMN ID_ISS_SETT_MOD_TYPE;

select * from DATABASECHANGELOG WHERE AUTHOR = 'rsarapura'
